### ISSUE TITLE
jobmanager failed

### ISSUE THREAD

**Issue by bochuxt** [hequn8128/pyflink-walkthrough#2]
jobmanager_1            | Caused by: java.io.IOException: Could not create storage directory for BLOB store in '/tmp'

**Comment by bochuxt** [comment]
taskmanager_1  | java.io.IOException: Could not create storage directory for BLOB store in '/tmp'.
taskmanager_1  |        at org.apache.flink.runtime.blob.BlobUtils.initLocalStorageDirectory(BlobUtils.java:154) ~[flink-dist_2.11-1.11.0.jar:1.11.0]
taskmanager_1  |        at org.apache.flink.runtime.blob.AbstractBlobCache.<init>(AbstractBlobCache.java:106) ~[flink-dist_2.11-1.11.0.jar:1.11.0]
taskmanager_1  |        at org.apache.flink.runtime.blob.PermanentBlobCache.<init>(PermanentBlobCache.java:104) ~[flink-dist_2.11-1.11.0.jar:1.11.0]
taskmanager_1  |        at org.apache.flink.runtime.blob.BlobCacheService.<init>(BlobCacheService.java:58) ~[flink-dist_2.11-1.11.0.jar:1.11.0]
taskmanager_1  |        at org.apache.flink.runtime.taskexecutor.TaskManagerRunner.<init>(TaskManagerRunner.java:149) ~[flink-dist_2.11-1.11.0.jar:1.11.0]
taskmanager_1  |        at org.apache.flink.runtime.taskexecutor.TaskManagerRunner.runTaskManager(TaskManagerRunner.java:305) ~[flink-dist_2.11-1.11.0.jar:1.11.0]
taskmanager_1  |        at org.apache.flink.runtime.taskexecutor.TaskManagerRunner.lambda$runTaskManagerSecurely$2(TaskManagerRunner.java:320) ~[flink-dist_2.11-1.11.0.jar:1.11.0]
taskmanager_1  |        at org.apache.flink.runtime.security.contexts.NoOpSecurityContext.runSecured(NoOpSecurityContext.java:30) ~[flink-dist_2.11-1.11.0.jar:1.11.0]
taskmanager_1  |        at org.apache.flink.runtime.taskexecutor.TaskManagerRunner.runTaskManagerSecurely(TaskManagerRunner.java:319) [flink-dist_2.11-1.11.0.jar:1.11.0]
taskmanager_1  |        at org.apache.flink.runtime.taskexecutor.TaskManagerRunner.main(TaskManagerRunner.java:297) [flink-dist_2.11-1.11.0.jar:1.11.0]
pyflink-walkthrough_taskmanager_1 exited with code 1
